### ISSUE TITLE
bash completion doesn't work without an option

### ISSUE THREAD

**Issue by rrthomas** [craig-sanders/dlocate#1]
I don't know why I've not noticed this before, since the package I have doesn't seem to have changed in the last couple of years (I'm an Ubuntu LTS version, and both trusty and xenial have 1.02nmu3), but if I type e.g.

dlocate /etc/ca-certificates<TAB>

then nothing happens.

I checked against git master, and dlocate-completion is identical there to the version I'm using.

**Comment by craig-sanders** [comment]
thanks for letting me know.  i'll look into it....but:
- I loathe bash-completion scripts (mostly because annoyances like this greatly outweigh the benefits), 
- I `apt-get purge bash-completion` on all my systems.
- I know almost nothing about how bash-completion scripts work or how to write them,

and
- The bash-completion script in `dlocate` was contributed by someone who submitted a bug report many years ago.  All of which means I probably won't get to it any time soon.

see:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=223718
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=658669

If you submit a pull request that seems even remotely sane :), i'll almost certainly merge it

**Comment by rrthomas** [comment]
I've submitted a PR.

As far as I can tell, the two Debian bugs you mention don't add anything, since one was the original bash-completion script, and the other was a fix to it four years ago, which was applied.

**Comment by craig-sanders** [comment]
Thanks, merged.  the bug reports were just for history on how bash-completion even got into dlocate in the first place.
